### ISSUE TITLE
Update All Algorithms Challenges

### ISSUE THREAD

**Issue by Rafase282** [FreeCodeCamp/wiki#1094]
# What we need:

We need all articles to follow this [template](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki/Wiki-Template-Challenge-Solution).

## What to watch out for:
There should be no more than three solutions, per challenge, we have to make sure that we provide explanations, and resources via links, either articles about built in functions that would be needed, algorithms, or anything related that can or was used to solve the problem.

## How to get started

1. Check for available articles, this means make sure no one is working on them already.
2. Ask to be assigned to any of the members on the **Assignees** list to the right. Non FCC team members cannot be added to this list, but we can add your name to it.
3. Once you get an assignment, let us know the link to the pull request, it will be added next to the challenge name along with your name.

## Adding links

First check the FCC challenge, they have general links used as hints, note them for those are the ones we must include. However, if we have our own resources [here](https://github.com/FreeCodeCamp/FreeCodeCamp/wiki) then use that instead. You do this by searching for the article. for example if you are looking for slice:

![search](https://i.imgur.com/NU4yJ1m.png)

Then you canuse that instead of an external resource. The template uses 3 links, but it can be fewer or more as needed.

When looking for links for the solutions, check which built in functions or specific algorithm is used and search our wiki for related articles, if none is found, only then use an external resource.

**Do not repeat links** 
If you already use a link in the general section or one of the solutions, then do not add it to another one in the same article.

## Adding code explanations

You try to explain it with your own words but not in a personal voice.

**Only 3 solutions are accepted**
If there are more than three then talk with us about which one to remove or merge at the [chat](https://gitter.im/FreeCodeCamp/Wiki).

> We don't need many of them and a maximum of three solutions will be accepted in the following categories:

>Basic
Intermediate
Advance
One code solution per category. If we already have enough solutions and yours is similar to one we already have but you strongly feel like yours will bring something important then we encourage you to merge your solution with the similar one we already have and expand or write a detailed explanation of the code.

## Challenges to be updated:

- [x] [Arguments Optional](https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-Arguments-Optional.md) (@Rafase282) #1093 
- [x] [Binary Agents](https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-Binary-Agents.md) (@atjonathan) #1099 
- [x] [Boo Who](https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-Boo-Who.md) (@atjonathan) #1098 
- [x] [Caesar's Cipher](https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-Caesars-Cipher.md) (@atjonathan) #1102 
- [x] [Check for Palindromes](https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-Check-For-Palindromes.md) (@atjonathan) #1101 
- [x] [Chunky Monkey](https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-Chunky-Monkey.md) (@atjonathan) #1100 
- [x] [Comfirm the Ending](https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-Confirm-The-Ending.md) (@atjonathan) #1104
- [x] [Convert HTML Entities](https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-Convert-HTML-Entities.md) (@atjonathan) #1105
- [x] [DNA Pairing](https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-DNA-Pairing.md) (@Rafase282) #1126
- [x] [Diff Two Arrays](https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-Diff-Two-Arrays.md) (@atjonathan) #1106
- [x] [Drop It](https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-Drop-It.md) (@Rafase282) #1116
- [x] [Everything Be True](https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-Everything-Be-True.md) (@koustuvsinha) #1110
- [x] [Exact Change](https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-Exact-Change.md) (@koustuvsinha) #1111
- [x] [Factorialize a Number](https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-Factorialize-A-Number.md) (@koustuvsinha) #1112
- [x] [Falsy Bouncer](https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-Falsy-Bouncer.md) (@koustuvsinha) #1113
- [x] [Find the largest word in a string](https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-Find-The-Longest-Word-In-A-String.md) (@koustuvsinha) #1114
- [x] [Finder's Keepers](https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-Finders-Keepers.md) (@dakshshah96 ) #1122 
- [x] [Friendly Dates Range](https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-Friendly-Date-Ranges.md) (@dakshshah96 ) #1154 
- [x] [Inventory Update](https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-Inventory-Update.md)  (@dakshshah96 ) #1170 
- [x] [Make a Person](https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-Make-A-Person.md) (@Rafase282) #1127
- [x] [Map the Debris](https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-Map-The-Debris.md) (@dakshshah96) #1161 
- [x] [Missing Letters](https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-Missing-Letters.md) (@dakshshah96) #1157 
- [x] [Mutations](https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-Mutations.md) (@Rafase282) #1128
- [x] [No Repeats Please](https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-No-Repeats-Please.md) (@dakshshah96) #1168 
- [x] [Pairwise](https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-Pairwise.md) (@dakshshah96) #1162 
- [x] [Pig latin](https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-Pig-Latin.md) (@dakshshah96 ) #1141 
- [x] [Repeat a string](https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-Repeat-A-String-Repeat-A-String.md) (@dakshshah96 ) #1124 
- [x] [Return largest Numbers in arrays](https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-Return-Largest-Numbers-In-Arrays.md) (@Rafase282) #1129
- [x] [Reverse a String](https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-Reverse-A-String.md) (@atjonathan) #1097
- [x] [Roman Numeral Converter](https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-Roman-Numeral-Converter.md) (@atjonathan) #1131 
- [x] [Search and Replace](https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-Search-And-Replace.md) (@dakshshah96 ) #1143 
- [x] [Seek and Destroy](https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-Seek-And-Destroy.md) (@Rafase282) #1130 
- [x] [Slasher Flick](https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-Slasher-Flick.md) (@dakshshah96 ) #1150 
- [x] [Smaller Common Multiple](https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-Smallest-Common-Multiple.md) (@dakshshah96 ) #1145 
- [x] [Sorted Union](https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-Sorted-Union.md) (@dakshshah96 ) #1153 
- [x] [Spinal Tap Case](https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-Spinal-Tap-Case.md) (@dakshshah96)
- [x] [Steamroller](https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-Steamroller.md) (@Rafase282) #1132 
- [x] [Sum all numbers in a range](https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-Sum-All-Numbers-In-A-Range.md) (@atjonathan) #1134
- [x] [Sum all odd fibonacci Numbers](https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-Sum-All-Odd-Fibonacci-Numbers.md) (@dakshshah96 ) #1137 
- [x] [Sum all primes](https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-Sum-All-Primes.md) (@dakshshah96 ) #1125 
- [x] [Symmetric Difference](https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-Symmetric-Difference.md) (@dakshshah96) #1164 
- [x] [Title Case a Sentence](https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-Title-Case-A-Sentence.md) (@dakshshah96 ) #1136 
- [x] [Truncate a string](https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-Truncate-A-String.md) (@bmorelli25) #1091 
- [x] [Validate US telephone numbers](https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-Validate-US-Telephone-Numbers.md) (@atjonathan) #1135  (@Rafase282) #1142 
- [x] [Where Art thou?](https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-Where-Art-Thou.md) ( @atjonathan ) #1159 
- [x] [Where do I belong?](https://github.com/FreeCodeCamp/wiki/blob/master/Algorithm-Where-Do-I-Belong.md) (@Rafase282) #1158

**Comment by dakshshah96** [comment]
@Rafase282 I'd like to be assigned on the algorithm challenge — Finder's Keepers. Thanks!

**Comment by Rafase282** [comment]
@dakshshah96 it is yours now.

**Comment by dakshshah96** [comment]
Pull request #1122 open for Finder's Keepers. I'd like to be assigned to — Repeat a String and Sum All Primes. Cheers!

**Comment by Rafase282** [comment]
@dakshshah96 I got you.

**Comment by dakshshah96** [comment]
Created PR #1124 for Repeat a String.

**Comment by dakshshah96** [comment]
Created PR #1125 for Sum All Primes.

@Rafase282 I'd like to be assigned to:
* Sum All Numbers in Range
* Sum All Odd Fibonacci Numbers
* Title Case a Sentence

**Comment by dakshshah96** [comment]
Please assign me to:
* Pig Latin
* Search and Replace

**Comment by dakshshah96** [comment]
Please assign me to the following if you can:
* Smallest Common Multiple
* Slasher Flicker
* Friendly Date Ranges
* Sorted Union

**Comment by dakshshah96** [comment]
Hey @Rafase282! Just noticed you haven't marked Slasher Flicker as completed in the checklist. And, isn't the name supposed to be Slasher Flick? The PR is #1150

**Comment by Rafase282** [comment]
@dakshshah96 thanks for pointing that out, renamed and added the PR as marked and with the right number.

**Comment by dakshshah96** [comment]
@Rafase282, please assign me to the following:
* Missing Letters
* Spinal Tap Case
* Map The Debris

Cheers!

**Comment by dakshshah96** [comment]
@Rafase282, assign me to the following if possible:
* Pairwise
* Symmetric Difference
* No Repeats Please
Cheers!

**Comment by dakshshah96** [comment]
@Rafase282 One more to go! Assign me to **Inventory Update** please.

**Comment by Rafase282** [comment]
Great work everyone, now we still need to do the checkpoint ones.

**Comment by atjonathan** [comment]
@Rafase282, is there any point now that we're moving to the forum :question:

**Comment by atjonathan** [comment]
Thanks @dakshshah96 for your work on this :tada:, it's greatly appreciated :smile:

**Comment by Rafase282** [comment]
Well they will have this format, I just forgot at the time.

**Comment by Rafase282** [comment]
Thank you everyone who worked on these, specially @dakshshah96
