### ISSUE TITLE
New Content for the Wiki

### ISSUE THREAD

**Issue by Rafase282** [FreeCodeCamp/wiki#367]
List is a work in progress.
Based off the most popular StackOverflow anwsers and my own choices so far.

# Git Related
- [ ] [Undo a commit and redo](http://stackoverflow.com/questions/927358/how-do-you-undo-the-last-commit/927386#927386)
- [ ] [Amending the most recent commit message](http://stackoverflow.com/questions/179123/edit-an-incorrect-commit-message-in-git/179147#179147)

# Backend Related
- [ ] API Authentication & Authorization

# Frontend Related
- [ ] [Page Redirect using Jquery](http://stackoverflow.com/questions/503093/how-can-i-make-a-page-redirect-using-jquery/506004#506004)

# Curriculum Specific

# Others

**Comment by QuincyLarson** [comment]
@Rafase282 This is an excellent start. These are the sorts of things I myself have looked up a number of times, so it would be great to be able to read them in a wiki format (rather than a stack overflow format, which is less user-friendly)

**Comment by hallaathrad** [comment]
Can I request we document how to setup a front-end dev environment?
How to set up PostCSS to concatenate JS, nest and prefix css etc; eslint, jshint, uglify, live reload, all these in a build system like gulp+bower.

It's been bugging me not really being able to find something decent like that, specifically thought for those who stick to the front.

**Comment by Rafase282** [comment]
@hallaathrad yes, just add it there.

**Comment by raisedadead** [comment]
#379 up for 
- [x]  Undo a commit and redo
- [x]  Delete a Git branch both locally and remotely
- [x]  Checkout Remote Branch
- [x]  Force Git to overwrite local files on pull

**Comment by Rafase282** [comment]
Guys, to make it easier for all of us, if you sent a PR for any of the issues here, mark it here, the same if you are creating an article, let us know by marking it. The only thing is that if for whatever reason it is not merged and it is closed then it will need to be unchecked.

Also adding more articles from the list on the gist is needed and appreciated.

**Comment by thomasvaeth** [comment]
I recently wrote a blog post on getting a basic front end dev environment set up. I can write something on the basics of Gulp today.

**Comment by hallaathrad** [comment]
@thomasvaeth you'll become my hero for the 15 minutes after you post it! I've been trying to get away from needing CodeKit for the longest while.

**Comment by Rafase282** [comment]
I'll look forward tot hat too.

**Comment by Rafase282** [comment]
@hallaathrad the filename is Gulp-Basics.md

**Comment by hallaathrad** [comment]
w0000t!

**Comment by austincarnivore** [comment]
I can work on some those Frontend related post.  I will try and knockout _Horizontally Center Div_ tomorrow.

**Comment by hallaathrad** [comment]
should we be updating these items to reflect their newly added link?

**Comment by Rafase282** [comment]
No, I prefer to have the original link for reference, no many list it as source, not everyone adds all the useful info either. Just checking them out is enough, maybe adding filename or link to the created article or PR as long as the original link remains.

**Comment by crisbnk** [comment]
Hi, I'll start with "Capitalize the first letter of string in JavaScript".

**Comment by awesomeaniruddh** [comment]
I believe an article on how scopes work in JavaScript could be useful. It won't be a long article, but it's essential to discuss scopes before we discuss the Global Object (https://github.com/FreeCodeCamp/wiki/issues/358). Could you add scopes to the checklist? An article already exists but it could be greatly improved.

**Comment by Rafase282** [comment]
@awesomeaniruddh added it and provided link to current article.

**Comment by jktravis** [comment]
Quick question. Are we to take the links and make them into articles, giving attribution to the source? So, basically a copy/paste of the links?

**Comment by Rafase282** [comment]
@jktravis yes and no. You could do a rewrite, explain it with your own words, or use a different source. We provide links so there is a source but you are not limited to its content alone.

**Comment by davidatthepark** [comment]
Hello, I'm a little new and would love to contribute. 
I'll start with "Discard unstaged changes"

@Rafase282 can you please clarify what you meant by "if you sent a PR, please mark it here."  Do you mean checking off the issue in the list? If so, I am not exactly sure how to do that...

**Comment by alayek** [comment]
@davidatthepark you can also talk to us in the [wiki](https://gitter.im/FreeCodeCamp/Wiki) chatroom. Just clone the repo locally, write your article in a new file that ends in `.md` extension, and raise a PR. Wait for the QA, and implement suggestions from the review (if any), and then we would merge.

I feel that you are already good with Git, but if you still need any help, do let us know in the [chatroom](https://gitter.im/FreeCodeCamp/Wiki).

**Comment by theflametrooper** [comment]
I'm working on:
- [ ] Clone a specific branch
- [ ] Rename Local Branch
- [ ] Clone all remote branches

**Comment by willnwhite** [comment]
The JS Closure example is a bad example. Why wouldn't you just `alert("Mozilla")`? The example is no more dynamic than that. Not that I can think of a better example off the top of my head, I'm just logging it.
