### ISSUE TITLE
Update function names to match main repository

### ISSUE THREAD

**Issue by erictleung** [FreeCodeCamp/wiki#615]
This issue, FreeCodeCamp/FreeCodeCamp#7085, is changing function names in the main repo and the corresponding Wiki challenges need to update their function names too. Refer back to that issue to see what challenges have been updated and then need to be updated in the Wiki. Reference this issue when making a change but do not close this issue.

#### Advanced Bonfires
- [x] [Algorithm Exact Change](https://github.com/FreeCodeCamp/wiki/pull/405) - #405
- [x] [Algorithm Inventory Update](https://github.com/FreeCodeCamp/wiki/pull/618) - #618
- [x] [Algorithm Friendly Date Ranges](https://github.com/FreeCodeCamp/wiki/pull/661) - #661

#### Basic Bonfires
- [x] [Algorithm Confirm the Ending](https://github.com/FreeCodeCamp/wiki/pull/661) - #661
- [x] [Algorithm Repeat a string repeat a string](https://github.com/FreeCodeCamp/wiki/pull/661) - #661
- [x] [Algorithm Truncate a string](https://github.com/FreeCodeCamp/wiki/pull/661) - #661
- [x] [Algorithm Chunky Monkey](https://github.com/FreeCodeCamp/wiki/pull/661) - #661
- [x] [Algorithm Where do I belong](https://github.com/FreeCodeCamp/wiki/pull/661) - #661

#### Basic JavaScript
- [x] [Algorithm Convert Celsius to Fahrenheit][PR703] - #703
- [ ] Challenge Write Reusable JavaScript with Functions (N/A)
- [x] [Challenge Passing Values to Functions with Arguments][PR703] - #703
- [x] [Challenge Local Scope and Functions][PR703] - #703
- [x] [Challenge Global vs. Local Scope in Functions][PR703] - #703
- [ ] Challenge	Assignment with a Returned Value (N/A)
- [x] [Algorithm Stand in Line][PR703] - #703
- [x] [Challenge Use Conditional Logic with If Statements][PR703] - #703
- [x] [Challenge Comparison with the Equality Operator][PR703] - #703
- [ ] Challenge Comparison with the Strict Equality Operator (N/A)
- [ ] Challenge Comparison with the Inequality Operator (N/A)
- [ ] Challenge Comparison with the Strict Inequality Operator (N/A)
- [ ] Challenge Comparison with the Greater Than Operator (N/A)
- [ ] Challenge	Comparison with the Greater Than Or Equal To Operator (N/A)
- [ ] Challenge	Comparison with the Less Than Operator (N/A)
- [ ] Challenge	Comparison with the Less Than Or Equal To Operator (N/A)
- [ ] Challenge	Comparisons with the Logical And Operator (N/A)
- [ ] Challenge	Comparisons with the Logical Or Operator (N/A)
- [ ] Challenge Introducing Else Statements (N/A)
- [ ] Challenge Introducing Else If Statements (N/A)
- [ ] Challenge Logical Order in If Else Statements (No article at all)
- [ ] Challenge Chaining If Else Statements (N/A)
- [ ] Challenge Selecting from many options with Switch Statements (N/A)
- [ ] Challenge Adding a default option in Switch statements (N/A)
- [ ] Challenge Multiple Identical Options in Switch Statements (N/A)
- [ ] Challenge Replacing If Else Chains with Switch (N/A)
- [x] [Algorithm Record Collection][PR703] - #703
- [x] [Algorithm Profile Lookup][PR703] - #703
- [ ] Challenge Generate Random Fractions with JavaScript (N/A)
- [ ] Challenge Generate Random Whole Numbers with JavaScript (N/A)
- [ ] Challenge Generate Random Whole Numbers within a Range (N/A)
- [ ] Challenge Create a JavaScript Slot Machine (N/A)
- [ ] Challenge Add your JavaScript Slot Machine Slots (N/A)
- [ ] Challenge Bring your JavaScript Slot Machine to Life (N/A)
- [ ] Challenge Give your JavaScript Slot Machine some Stylish Images (N/A)

#### Intermediate Bonfires
- [x] [Algorithm Diff Two Arrays][PR703] - #703
- [x] [Algorithm Roman Numeral Converter][PR703] - #703
- [x] [Algorithm Where art thou][PR703] - #703
- [x] [Algorithm Pig Latin][PR703] - #703
- [x] [Algorithm DNA Pairing][PR703] - #703
- [x] [Algorithm Boo who][PR703] - #703
- [x] [Algorithm Sorted Union][PR703] - #703
- [x] [Algorithm Convert HTML Entities][PR703] - #703
- [x] [Algorithm Finders Keepers][PR703] - #703
- [x] [Algorithm Drop it][PR703] - #703
- [x] [Algorithm Everything Be True][PR703] - #703
- [x] [Algorithm Arguments Optional][PR703] - #703

[PR703]: https://github.com/FreeCodeCamp/wiki/pull/703/

**Comment by Saerith** [comment]
Created pull request for the remainder of the "Needs Changing" list, [pull 661](https://github.com/FreeCodeCamp/wiki/pull/661).

**Comment by Saerith** [comment]
I'll start through the rest of these today.

**Comment by Rafase282** [comment]
What is the status on this @erictleung @Saerith ?

**Comment by erictleung** [comment]
@Rafase282 I haven't been side-tracked with other stuff lately. I think we've covered mostly the challenges that needed to. Some don't require changes because there is no function. I can double check them over the weekend.

**Comment by Rafase282** [comment]
Alright, please do and let us know.

**Comment by erictleung** [comment]
@Rafase282 I just went through the unchecked ones. Looks like everything has been updated with new function names so I'm closing this issue.

**Comment by Rafase282** [comment]
Awesome, thanks.
